import type { Viewport } from 'next'
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "@/components/ui/toaster"

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "To Do App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: '#9395D3',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-gray-100 mx-auto flex justify-center h-screen py-10`}>
        <main className="w-full md:w-[440px] mx-auto bg-white overflow-hidden rounded-xl shadow-md">
          <Header />
        {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
